site_name: Портфолио проекта «Имя ребёнку»
site_description: Персональный сайт проекта подбора благозвучных имён (ИТМО, ФТМИ)
site_author: Нохрин Валерий Витальевич
site_url: https://valeriinohrin.github.io/portfolio-nohrin/

theme:
 name: mkdocs
  language: ru
  palette:
    scheme: default
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Главная: index.md
  - О проекте: about.md
  - Проекты: projects.md
  - Достижения: achivments.md
  - Резюме: resume.md
  - Контакты: contacts.md

extra_css:
  - styles/extra.css
